// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmjcbqqqZ-nEog5EJI2pba3RSVm-jgWVg',
    appId: '1:1014331050264:web:951cc8375cfe195fed766d',
    messagingSenderId: '1014331050264',
    projectId: 'up2110125-project',
    authDomain: 'up2110125-project.firebaseapp.com',
    storageBucket: 'up2110125-project.appspot.com',
    measurementId: 'G-5MYJH4N2ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1WHpHkX9Z8O3OwB2NgHRBsSgiwupK58',
    appId: '1:1014331050264:android:75284b93c5352b01ed766d',
    messagingSenderId: '1014331050264',
    projectId: 'up2110125-project',
    storageBucket: 'up2110125-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHARgmJCUoneS4qtDFy3DgUsKcQnRLGl4',
    appId: '1:1014331050264:ios:cb560f2d063b046ded766d',
    messagingSenderId: '1014331050264',
    projectId: 'up2110125-project',
    storageBucket: 'up2110125-project.appspot.com',
    iosBundleId: 'com.example.vsFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHARgmJCUoneS4qtDFy3DgUsKcQnRLGl4',
    appId: '1:1014331050264:ios:878cdf2ae4a00b0eed766d',
    messagingSenderId: '1014331050264',
    projectId: 'up2110125-project',
    storageBucket: 'up2110125-project.appspot.com',
    iosBundleId: 'com.example.vsFlutter2.RunnerTests',
  );
}
